app:
  pagination-limit: 20
  kafka:
    kafkaReservationTopic: "reservation"
    kafkaUserTopic: "user"
    kafkaMessageGroupId: "kafka-message-group-id"

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: statistics_db
    jpa:
      repositories:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db
    username: postgres
    password: postgres
    hikari:
      schema: hotel_reservation_schema
      data-source-properties:
        rewriteBatchedStatements: true
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jakarta:
          persistence:
            schema-generation:
              create-database-schemas: true
        hbm2ddl:
          auto: create
          create_namespaces: true
        format_sql: true
        default_schema: hotel_reservation_schema
        transaction:
          jta:
            platform: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform

  jackson:
    serialization:
      write-null-map-values: false
      write-empty-json-arrays: false

  security:
    user:
      name: admin
      password: 1308cf51-8da1-4aa0-966f-f3c0d0b066e7
      roles: ADMIN

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org:
      springframework:
        aop: DEBUG